apiVersion: v2
name: kubernetes-event-exporter
description: Export Kubernetes events to multiple destinations with routing and filtering
type: application
version: 0.1.6
appVersion: "1.7"
home: https://github.com/resmoio/kubernetes-event-exporter
sources:
  - https://github.com/resmoio/kubernetes-event-exporter
  - https://github.com/obezpalko/kubernetes-event-exporter
maintainers:
  - name: obezpalko
    url: https://github.com/obezpalko
keywords:
  - kubernetes
  - events
  - monitoring
  - prometheus
